### PR TITLE
Added NEI subsets localization

### PR DESCRIPTION
**Pull request by labpaw**
Also translated into Russian.

### CODE REVIEW

**Comment by heldplayer** [comment]
Is this actually a feature that NEI supports? :o

**Comment by labpaw** [comment]
yes, it was added in [latest version](https://github.com/Chicken-Bones/NotEnoughItems/commit/d59b28f8fcce1b55af02e3429b522b6062f08643).

**Comment by heldplayer** [comment]
Sweet!

EDIT: Could you possibly add newlines at the end of the files you changed?

**Comment by labpaw** [comment]
Done

**Comment by labpaw** [comment]
Better I should create new PR. Hold on.

**Pull request closed without merging**
